# Generated by Django 3.2.12 on 2023-10-23 16:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=20, verbose_name='фамилия')),
                ('name', models.CharField(max_length=20, verbose_name='имя')),
                ('patronymic', models.CharField(max_length=20, verbose_name='отчество')),
                ('photo', models.ImageField(blank=True, upload_to='photo_employee', verbose_name='фото')),
                ('post', models.CharField(max_length=20, verbose_name='должность')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='оклад')),
                ('age', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(60), django.core.validators.MinValueValidator(20)], verbose_name='возраст')),
            ],
            options={
                'verbose_name': 'сотрудники',
                'verbose_name_plural': 'сотрудник',
                'ordering': ('surname', 'name'),
            },
        ),
    ]
